import { describe, expect, it } from 'vitest'
import fs from 'fs'
import { AVAILABLE_CALCULATORS, CALCULATOR_TOOLS } from '../lib/calculators.js'
import { AVAILABLE_CONVERTERS } from '../lib/converters.js'
import { AVAILABLE_DOCUMENT_TOOLS } from '../lib/document-tools.js'
import { PUBLIC_ROUTES } from '../lib/site.js'
const read=(path)=>fs.readFileSync(path,'utf8')

describe('calculator discovery and content',()=>{
  it('publishes every available calculator through a public route',()=>{expect(CALCULATOR_TOOLS.length).toBeGreaterThanOrEqual(26);expect(AVAILABLE_CALCULATORS.length).toBe(CALCULATOR_TOOLS.filter(({available})=>available).length);for(const calculator of AVAILABLE_CALCULATORS){expect(calculator.href.startsWith('/calculators/')).toBe(true);expect(PUBLIC_ROUTES).toContain(calculator.href);expect(fs.existsSync(`app${calculator.href}/page.js`)).toBe(true)}expect(AVAILABLE_CALCULATORS.map(({id})=>id)).toEqual(expect.arrayContaining(['percentage','loan','interest','scientific','discount','bmi','gpa']))})
  it('integrates calculator, converter, and document discovery without removing PDF search',()=>{const search=read('components/tooliyapa/ToolSearch.js');const home=read('components/tooliyapa/HomePage.js');const header=read('components/tooliyapa/Header.js');const footer=read('components/tooliyapa/Footer.js');expect(search).toContain('...PDF_TOOLS, ...AVAILABLE_CALCULATORS, ...AVAILABLE_CONVERTERS, ...AVAILABLE_DOCUMENT_TOOLS');expect(home).toContain('href="/calculators"');expect(home).toContain('href="/converters"');expect(home).toContain('href="/documents"');expect(header).toContain('href="/calculators"');expect(header).toContain('href="/converters"');expect(header).toContain('href="/documents"');expect(footer).toContain("['Calculators','/calculators']");expect(footer).toContain("['Converters','/converters']");expect(footer).toContain("['Documents','/documents']");expect(header).toContain("const FUTURE_CATEGORIES = ['Text']");expect(AVAILABLE_CONVERTERS.length).toBeGreaterThanOrEqual(18);expect(AVAILABLE_DOCUMENT_TOOLS).toHaveLength(14)})
  it('provides substantive original percentage guidance without social proof',()=>{const page=read('app/calculators/percentage/page.js');for(const heading of ['What is a percentage?','Percentage formulas','How percentage change works','Practical examples','Common mistakes','Frequently asked questions'])expect(page).toContain(heading);expect(page).not.toMatch(/most popular|used by thousands|best calculator|CalcSuite/i)})
  it('provides substantive loan guidance and clear assumptions',()=>{const page=read('app/calculators/loan/page.js');for(const heading of ['How the loan payment is calculated','What EMI means','What extra monthly payments do','Important assumptions','Why lender figures may differ','Frequently asked questions','Use as an estimate'])expect(page).toContain(heading);expect(page).toContain('It is not financial advice');expect(page).not.toMatch(/most popular|used by thousands|best calculator|CalcSuite/i)})
})
