import Link from 'next/link'
import { ArrowRight, FileArchive, FileText, ShieldCheck } from 'lucide-react'
import { Card } from '@/components/ui/card'
import DocumentToolClient from '@/components/tooliyapa/DocumentToolClient'
import { DOCUMENT_PAGES, AVAILABLE_DOCUMENT_TOOLS } from '@/lib/document-tools'

const iconFor = (tool) => tool.output === 'EPUB' || tool.output === 'Images / ZIP' ? FileArchive : FileText

export function DocumentCard({ tool }) {
  const Icon=iconFor(tool)
  return <Link href={tool.href} className="group rounded-2xl focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-blue-600 focus-visible:ring-offset-2"><Card className="h-full rounded-2xl border border-slate-200 bg-white p-5 shadow-sm transition group-hover:-translate-y-0.5 group-hover:border-blue-300 group-hover:shadow-md dark:border-slate-800 dark:bg-slate-900"><div className="flex items-start justify-between gap-3"><span className="rounded-xl bg-blue-50 p-2.5 text-blue-700 dark:bg-blue-950/40 dark:text-blue-300"><Icon className="h-5 w-5" aria-hidden="true"/></span><span className="rounded-full bg-slate-100 px-2.5 py-1 text-[10px] font-semibold uppercase tracking-wide text-slate-600 dark:bg-slate-800 dark:text-slate-300">{tool.input} → {tool.output}</span></div><h3 className="mt-4 text-base font-bold text-slate-900 dark:text-white">{tool.title}</h3><p className="mt-2 text-sm leading-6 text-slate-600 dark:text-slate-400">{tool.description}</p><div className="mt-5 flex items-center gap-1 text-sm font-semibold text-blue-700 dark:text-blue-300">Open tool <ArrowRight className="h-4 w-4 transition-transform group-hover:translate-x-0.5"/></div></Card></Link>
}

export function DocumentsCategoryPage() {
  const groups=['Word conversions','Word inspection','Markdown & text','Document conversions'].map((name)=>({name,tools:AVAILABLE_DOCUMENT_TOOLS.filter((tool)=>tool.subcategory===name)})).filter((group)=>group.tools.length)
  return <main id="main-content" className="mx-auto max-w-7xl px-4 py-12 sm:px-6 sm:py-16"><div className="max-w-3xl"><p className="text-xs font-semibold uppercase tracking-[0.18em] text-blue-700 dark:text-blue-400">Documents</p><h1 className="mt-2 text-3xl font-bold tracking-tight text-slate-900 dark:text-white sm:text-4xl">Free Online Document Tools</h1><p className="mt-4 text-base leading-7 text-slate-600 dark:text-slate-300">Convert, inspect, extract, and reformat common document files directly in your browser. The current tools focus on DOCX, Markdown, PDF text, plain text, and XLSX-to-CSV workflows.</p><div className="mt-6 flex flex-wrap gap-3"><span className="rounded-full bg-blue-50 px-3 py-1.5 text-sm font-semibold text-blue-800 dark:bg-blue-950/50 dark:text-blue-300">{AVAILABLE_DOCUMENT_TOOLS.length} document tools available</span><span className="inline-flex items-center gap-1.5 text-sm text-slate-500 dark:text-slate-400"><ShieldCheck className="h-4 w-4"/>Local browser processing</span></div></div><div className="mt-12 space-y-12">{groups.map((group)=><section key={group.name} aria-labelledby={`documents-${group.name.replace(/\W+/g,'-').toLowerCase()}`}><h2 id={`documents-${group.name.replace(/\W+/g,'-').toLowerCase()}`} className="text-2xl font-bold text-slate-900 dark:text-white">{group.name}</h2><div className="mt-5 grid gap-5 sm:grid-cols-2 lg:grid-cols-3">{group.tools.map((tool)=><DocumentCard key={tool.id} tool={tool}/>)}</div></section>)}</div><section className="mt-14 rounded-2xl border border-blue-100 bg-blue-50/50 p-6 dark:border-blue-950 dark:bg-blue-950/20"><h2 className="text-xl font-bold text-slate-900 dark:text-white">Privacy and compatibility</h2><p className="mt-3 text-sm leading-7 text-slate-600 dark:text-slate-300">These document tools process selected files in browser memory. They do not upload document bytes to a Tooliyapa conversion server. Complex office formats can contain features that browsers cannot reproduce exactly, so each tool explains its own limits and the generated output should be reviewed before publication or formal use.</p></section></main>
}

export function DocumentToolPage({ toolId }) {
  const tool=DOCUMENT_PAGES[toolId]
  if(!tool)throw new Error(`Unknown document tool: ${toolId}`)
  const related=AVAILABLE_DOCUMENT_TOOLS.filter((item)=>item.id!==tool.id&&item.subcategory===tool.subcategory).slice(0,3)
  return <main id="main-content" className="mx-auto max-w-6xl px-4 py-10 sm:px-6 sm:py-14"><nav aria-label="Breadcrumb" className="text-sm text-slate-500 dark:text-slate-400"><Link href="/" className="hover:text-blue-700">Home</Link><span className="mx-2">/</span><Link href="/documents" className="hover:text-blue-700">Documents</Link><span className="mx-2">/</span><span aria-current="page">{tool.title}</span></nav><header className="mt-7 max-w-3xl"><div className="inline-flex rounded-full bg-blue-50 px-3 py-1 text-xs font-semibold uppercase tracking-wide text-blue-800 dark:bg-blue-950/50 dark:text-blue-300">{tool.input} → {tool.output}</div><h1 className="mt-4 text-3xl font-bold tracking-tight text-slate-900 dark:text-white sm:text-4xl">{tool.title}</h1><p className="mt-4 text-base leading-7 text-slate-600 dark:text-slate-300">{tool.description}</p></header><section className="mt-8" aria-label={`${tool.title} workspace`}><DocumentToolClient toolId={tool.id}/></section><div className="mt-12 grid gap-6 lg:grid-cols-2"><section className="rounded-2xl border border-slate-200 bg-white p-6 dark:border-slate-800 dark:bg-slate-900"><h2 className="text-xl font-bold text-slate-900 dark:text-white">What this tool does</h2><p className="mt-3 text-sm leading-7 text-slate-600 dark:text-slate-300">{tool.about}</p></section><section className="rounded-2xl border border-amber-200 bg-amber-50/50 p-6 dark:border-amber-950 dark:bg-amber-950/20"><h2 className="text-xl font-bold text-slate-900 dark:text-white">What to expect</h2><p className="mt-3 text-sm leading-7 text-slate-600 dark:text-slate-300">{tool.limitations}</p></section></div><section className="mt-8 rounded-2xl border border-emerald-100 bg-emerald-50/50 p-6 dark:border-emerald-950 dark:bg-emerald-950/20"><h2 className="text-xl font-bold text-slate-900 dark:text-white">Browser-based privacy</h2><p className="mt-3 text-sm leading-7 text-slate-600 dark:text-slate-300">The selected source content is processed locally in this browser for this document workflow. Tooliyapa does not send the file to a document-conversion backend. Generated downloads are created on your device. Browser memory and device performance still limit very large or unusually complex files.</p></section>{related.length>0&&<section className="mt-12"><h2 className="text-2xl font-bold text-slate-900 dark:text-white">Related document tools</h2><div className="mt-5 grid gap-5 sm:grid-cols-2 lg:grid-cols-3">{related.map((item)=><DocumentCard key={item.id} tool={item}/>)}</div></section>}</main>
}
