import Link from 'next/link'
import { ArrowRight, ShieldCheck, Type } from 'lucide-react'
import { Card } from '@/components/ui/card'
import TextToolClient from '@/components/tooliyapa/TextToolClient'
import { AVAILABLE_TEXT_TOOLS, TEXT_PAGES } from '@/lib/text-tools'

export function TextCard({ tool }) {
  return <Link href={tool.href} className="group rounded-2xl focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-violet-600 focus-visible:ring-offset-2"><Card className="h-full rounded-2xl border border-slate-200 bg-white p-5 shadow-sm transition group-hover:-translate-y-0.5 group-hover:border-violet-300 group-hover:shadow-md dark:border-slate-800 dark:bg-slate-900"><div className="flex items-start justify-between gap-3"><span className="rounded-xl bg-violet-50 p-2.5 text-violet-700 dark:bg-violet-950/40 dark:text-violet-300"><Type className="h-5 w-5" aria-hidden="true"/></span><span className="rounded-full bg-slate-100 px-2.5 py-1 text-[10px] font-semibold uppercase tracking-wide text-slate-600 dark:bg-slate-800 dark:text-slate-300">Browser tool</span></div><h3 className="mt-4 text-base font-bold text-slate-900 dark:text-white">{tool.title}</h3><p className="mt-2 text-sm leading-6 text-slate-600 dark:text-slate-400">{tool.description}</p><div className="mt-5 flex items-center gap-1 text-sm font-semibold text-violet-700 dark:text-violet-300">Open tool <ArrowRight className="h-4 w-4 transition-transform group-hover:translate-x-0.5" aria-hidden="true"/></div></Card></Link>
}

export function TextCategoryPage() {
  const groups=['Count & analyze','Transform & clean','Compare & review','Generate & summarize'].map((name)=>({name,tools:AVAILABLE_TEXT_TOOLS.filter((tool)=>tool.subcategory===name)})).filter((group)=>group.tools.length)
  return <main id="main-content" className="mx-auto max-w-7xl px-4 py-12 sm:px-6 sm:py-16"><div className="max-w-3xl"><p className="text-xs font-semibold uppercase tracking-[0.18em] text-violet-700 dark:text-violet-400">Text tools</p><h1 className="mt-2 text-3xl font-bold tracking-tight text-slate-900 dark:text-white sm:text-4xl">Free Online Text Tools</h1><p className="mt-4 text-base leading-7 text-slate-600 dark:text-slate-300">Count, compare, transform, analyze, and summarize text with transparent browser-based utilities. These tools run locally on the text you enter and do not require an account.</p><div className="mt-6 flex flex-wrap gap-3"><span className="rounded-full bg-violet-50 px-3 py-1.5 text-sm font-semibold text-violet-800 dark:bg-violet-950/50 dark:text-violet-300">{AVAILABLE_TEXT_TOOLS.length} text tools available</span><span className="inline-flex items-center gap-1.5 text-sm text-slate-500 dark:text-slate-400"><ShieldCheck className="h-4 w-4" aria-hidden="true"/>Local browser processing</span></div></div><div className="mt-12 space-y-12">{groups.map((group)=><section key={group.name} aria-labelledby={`text-${group.name.replace(/\W+/g,'-').toLowerCase()}`}><h2 id={`text-${group.name.replace(/\W+/g,'-').toLowerCase()}`} className="text-2xl font-bold text-slate-900 dark:text-white">{group.name}</h2><div className="mt-5 grid gap-5 sm:grid-cols-2 lg:grid-cols-3">{group.tools.map((tool)=><TextCard key={tool.id} tool={tool}/>)}</div></section>)}</div><section className="mt-14 rounded-2xl border border-violet-100 bg-violet-50/50 p-6 dark:border-violet-950 dark:bg-violet-950/20"><h2 className="text-xl font-bold text-slate-900 dark:text-white">Transparent local processing</h2><p className="mt-3 text-sm leading-7 text-slate-600 dark:text-slate-300">Tooliyapa&apos;s text utilities operate in your browser and do not send the text you enter to a Tooliyapa text-processing backend. Some tools use heuristics or simple statistical rules, so their pages explain what each result means and what it does not mean.</p></section></main>
}

export function TextToolPage({ toolId }) {
  const tool=TEXT_PAGES[toolId]
  if(!tool)throw new Error(`Unknown text tool: ${toolId}`)
  const related=AVAILABLE_TEXT_TOOLS.filter((item)=>item.id!==tool.id&&item.subcategory===tool.subcategory).slice(0,3)
  return <main id="main-content" className="mx-auto max-w-6xl px-4 py-10 sm:px-6 sm:py-14"><nav aria-label="Breadcrumb" className="text-sm text-slate-500 dark:text-slate-400"><Link href="/" className="hover:text-violet-700">Home</Link><span className="mx-2">/</span><Link href="/text" className="hover:text-violet-700">Text</Link><span className="mx-2">/</span><span aria-current="page">{tool.title}</span></nav><header className="mt-7 max-w-3xl"><div className="inline-flex rounded-full bg-violet-50 px-3 py-1 text-xs font-semibold uppercase tracking-wide text-violet-800 dark:bg-violet-950/50 dark:text-violet-300">Runs in your browser</div><h1 className="mt-4 text-3xl font-bold tracking-tight text-slate-900 dark:text-white sm:text-4xl">{tool.title}</h1><p className="mt-4 text-base leading-7 text-slate-600 dark:text-slate-300">{tool.description}</p></header><section className="mt-8" aria-label={`${tool.title} workspace`}><TextToolClient toolId={tool.id}/></section><div className="mt-12 grid gap-6 lg:grid-cols-2"><section className="rounded-2xl border border-slate-200 bg-white p-6 dark:border-slate-800 dark:bg-slate-900"><h2 className="text-xl font-bold text-slate-900 dark:text-white">What this tool does</h2><p className="mt-3 text-sm leading-7 text-slate-600 dark:text-slate-300">{tool.about}</p></section><section className="rounded-2xl border border-amber-200 bg-amber-50/50 p-6 dark:border-amber-950 dark:bg-amber-950/20"><h2 className="text-xl font-bold text-slate-900 dark:text-white">What to expect</h2><p className="mt-3 text-sm leading-7 text-slate-600 dark:text-slate-300">{tool.limitations}</p></section></div><section className="mt-8 rounded-2xl border border-emerald-100 bg-emerald-50/50 p-6 dark:border-emerald-950 dark:bg-emerald-950/20"><h2 className="text-xl font-bold text-slate-900 dark:text-white">Browser-based privacy</h2><p className="mt-3 text-sm leading-7 text-slate-600 dark:text-slate-300">The text you enter is processed locally by this browser tool. Tooliyapa does not send it to a text-processing backend as part of this workflow. Normal website delivery, advertising, consent, and other third-party services operate separately from the tool logic; see the Privacy Policy for the broader site data picture.</p></section>{related.length>0&&<section className="mt-12"><h2 className="text-2xl font-bold text-slate-900 dark:text-white">Related text tools</h2><div className="mt-5 grid gap-5 sm:grid-cols-2 lg:grid-cols-3">{related.map((item)=><TextCard key={item.id} tool={item}/>)}</div></section>}</main>
}
