export const CALCULATOR_TOOLS = [
  {
    id: 'percentage',
    title: 'Percentage Calculator',
    description: 'Calculate percentages, percentage change, and increases or decreases.',
    href: '/calculators/percentage',
    category: 'Calculators',
    keywords: 'percentage percent percentage calculator percent change percentage increase percentage decrease',
    available: true,
  },
  {
    id: 'loan',
    title: 'Loan / EMI Calculator',
    description: 'Estimate monthly payments, total interest, payoff time, and the effect of extra payments.',
    href: '/calculators/loan',
    category: 'Calculators',
    keywords: 'loan emi monthly payment repayment interest amortization extra payment finance calculator',
    available: true,
  },
  {
    id: 'interest',
    title: 'Interest Calculator',
    description: 'Compare simple and compound interest, APY, and recurring contribution growth.',
    href: '/calculators/interest',
    category: 'Calculators',
    keywords: 'interest calculator simple interest compound interest apy annual percentage yield recurring contribution savings investment',
    available: true,
  },
  {
    id: 'profit-margin',
    title: 'Profit Margin Calculator',
    description: 'Calculate profit, margin, markup, revenue, and cost from unit economics.',
    href: '/calculators/profit-margin',
    category: 'Calculators',
    keywords: 'profit margin markup selling price cost revenue business calculator gross margin',
    available: true,
  },
  {
    id: 'tip',
    title: 'Tip Calculator',
    description: 'Calculate tip amount, bill total, and per-person amounts when splitting a bill.',
    href: '/calculators/tip',
    category: 'Calculators',
    keywords: 'tip calculator gratuity bill split restaurant tip percentage per person',
    available: true,
  },
  {
    id: 'basic',
    title: 'Basic Calculator',
    description: 'Perform addition, subtraction, multiplication, division, powers, and remainders.',
    href: '/calculators/basic',
    category: 'Calculators',
    keywords: 'basic calculator arithmetic add subtract multiply divide power modulo remainder math',
    available: true,
  },
  {
    id: 'statistics',
    title: 'Statistics Calculator',
    description: 'Find mean, median, mode, range, variance, standard deviation, and common means.',
    href: '/calculators/statistics',
    category: 'Calculators',
    keywords: 'statistics calculator mean median mode range variance standard deviation geometric harmonic average dataset',
    available: true,
  },
]

export const AVAILABLE_CALCULATORS = CALCULATOR_TOOLS.filter(({ available }) => available)
